version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: nginx
    ports: 
      - "8083:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/conf.d/
    depends_on: 
      - php
      - mysql
    networks: 
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "3306:3306"
    volumes: 
      - ./database:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: sistemaarmada
      MYSQL_USER: sistemaarmada
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_NAME: mysql
    networks: 
      - laravel

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    container_name: php
    environment: 
      SERVICE_NAME: php
    volumes: 
      - ./src/:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks: 
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local